default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('DATABASE_USER', 'username') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'password') %>

development:
  <<: *default
  database: ads_development

test:
  <<: *default
  database: ads_test
